### ISSUE TITLE
Proper Behavior of `undo`

### ISSUE THREAD

**Issue by ywwry66** [davidshepherd7/electric-operator#100]
Using `undo` after typing a registered operator would only undo the effects of the `electric-operator` expansion, which is the behavior discussed in #51 and implemented in afa6283. While I think this is a good idea, I believe it can be implemented in a better way.

What `undo` does across Emacs is usually to revert the textual changes brought by the last command/keystroke (except for those amalgamating commands like `self-insert-command` and `delete-char`). To keep this consistent, in `electric-operator`, if I type `1` and `+` and `1` followed by two `undo`'s, I would expect the following sequence of strings:
`1`
`1 + `
`1 + 1`
`1 + `
`1`
You can find similar behavior of `undo` with the built-in `electric-indent` and `electric-pair` modes.

To achieve this, you only need two `(undo-boundary)`'s, one after
https://github.com/davidshepherd7/electric-operator/blob/9856ff8e1351086d0d738c1db300af63d6c085ba/electric-operator.el#L411
and the other after
https://github.com/davidshepherd7/electric-operator/blob/9856ff8e1351086d0d738c1db300af63d6c085ba/electric-operator.el#L423

For the purpose of undoing the effects of the `electric-operator` expansion, I think it is a good idea to write a dedicated interactive function `electric-operator-undo`, which can be later bound to favorite keys by the user.

**Comment by davidshepherd7** [comment]
Hi! I think the behaviour that you want seems reasonable, but it doesn't seem to be the Emacs default. If I disable electric operator mode I get:

```
1
1 +
1 + 1
    ;; One undo removes everything
```

So I think implementing this behaviour is outside the scope of electric-operator, but I think you could write a fairly simple `post-self-insert-hook` function to add the undo boundaries that you want.

Adding a configuration variable to disable the undo boundary seems like something we could do though, do you think that would be useful?
