### ISSUE TITLE
Remove (cons ":" ": ") from the rules for css-mode

### ISSUE THREAD

**Issue by akirak** [davidshepherd7/electric-operator#103]
There is a rule inserting space after every colon in css-mode, but I don't always want this. It's useful when you write properties, but not when you write [pseudo classes](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes).

Can you remove the rule? It would be better if there were a function for removing particular rules. 

An ideal solution would be to support *contextual rules*, but it would complicate the implementation, so I don't need that.

**Comment by davidshepherd7** [comment]
Hi, yeah that seems like a good idea.

Question: are colons outside of {} always pseudoclasses and inside {} are
they always properties? If so then it would be really easy for me to make
it contextual.

**Comment by akirak** [comment]
> Question: are colons outside of {} always pseudoclasses and inside {} are
they always properties? 

I think this is the case with `css-mode`, but not with SASS/SCSS, where one can define nested rule sets. In that case, there may be pseudo-classes inside a brace pair.

FYI: There is `css--colon-inside-selector-p` function in `css-mode`, which would be useful for determining the context. However, this is apparently meant to be a private function (because it is infixed with two hyphens), so I am not sure it is safe to use it.

**Comment by davidshepherd7** [comment]
Hi again, thanks for reporting this and sorry it took me a long time to get around to looking into it.

It should be working properly in CSS now (for both properties and psuedoclasses), I couldn't think of a way to make it work for SCSS so it's just disabled there. Let me know how it goes :)

**Comment by akirak** [comment]
That's okay for me, thanks for your consideration!
