### ISSUE TITLE
Python and lambda

### ISSUE THREAD

**Issue by muffinmad** [davidshepherd7/electric-operator#109]
The word `lambda` used a part of the other word leads to wrong spacing

## Reproducing

Open python file and type `foolambdabar=1`

### Expected result

```
foolambdabar = 1
```

### Actual result

```
foolambdabar=1
```

**Comment by davidshepherd7** [comment]
Thanks for reporting this, should be fixed now :)

**Comment by muffinmad** [comment]
Thanks! The `foolambda = 1` is fixed now. But looks like `lambdafoo=1` need some more attention ;)

**Comment by davidshepherd7** [comment]
Oh whoops, that case should be fixed too now. Thanks!

**Comment by muffinmad** [comment]
And one more case with lambdas ;)

Type `foo(lambda x:`

Expected result `foo(lambda x: |`

Actual result `foo(lambda x:|`

**Comment by davidshepherd7** [comment]
Thanks, there was a mistake in my implementation. That should also be fixed now.
