### ISSUE TITLE
coffee-mode support

### ISSUE THREAD

**Issue by jasonm23** [davidshepherd7/electric-operator#12]
I'll be adding this myself, just opening an issue to let anyone else interested know.

**Comment by davidshepherd7** [comment]
Great, let me know if you have any questions or problems :+1:

**Comment by davidshepherd7** [comment]
Hi, did you get this working? If it's fairly simple (i.e. you didn't need to write any lisp code) I'd be interested in merging it in.

**Comment by jasonm23** [comment]
Hi @davidshepherd7 I didn't get around to this because looking at the code, I felt that there should be better abstraction to separate different rules for each specific mode.

However, I didn't think too hard about how that might be do-able.

Hopefully you'll agree that extending this for dozens of different prog modes is going to get messy, fast.

Anyway, as a result, this probably spawns a new issue to re-structure / re-write the mode to make it more easily extensible.  

Interested to know your thoughts on this.

**Comment by davidshepherd7** [comment]
Hi, yeah I'm interested in improving things in general but I'm not quite sure what you want to improve (in particular what do you mean by "an abstraction to separate different rules for each specific mode").

For the sake of comparison here's an implementation of support for coffee mode (or at least the basics, I've probably missed some subtle cases because I don't know the language):

    ;; Coffee script support based on http://coffeescript.org/#operators
    (apply #'add-rules-for-mode 'coffee-mode prog-mode-rules)
    (add-rules-for-mode 'coffee-mode
                        (cons "**" " ** ")
                        (cons "//" " // ")
                        (cons "///" " /// ")
                        (cons "%%" " %% ")
                        (cons "?" "? ")
                        (cons "?=" " ?= ")
                        (cons "?." "?.")
                        (cons "->" " -> ")
                        (cons "=>" " => ")
                        )

This goes inside `electric-operator.el`, or could go into an init file with the addition of some `electric-operator-` prefixes. This addition has no effect on modes other than those derived from `coffee-mode`.

Can explain or show what you would like to write to achieve the same thing?

Thanks :+1:

**Comment by jasonm23** [comment]
Hey,

> an abstraction to separate different rules for each specific mode.

To expand on that. I was thinking about how to make it easier to add new rules.

Your coffee-mode example looks much simpler than I assumed it needed to be. Do I assume correctly that this form can be evaluated after the mode, and it will add the rules?

The way I originally assumed, I thought it was necessary to add additional rules directly into the mode.

I'm on my phone at the moment, but I'll try to describe this with line refs, if I'm not communicating this clearly enough.

**Comment by davidshepherd7** [comment]
> Do I assume correctly that this form can be evaluated after the mode, and it will add the rules? The way I originally assumed, I thought it was necessary to add additional rules directly into the mode.

Yep, you can put it where ever you like or just eval it directly. 

The only catch is that I'm using [`names`](https://github.com/Malabarba/names) for namespacing so if you put it outside of the electric-operator namespace you need to add the namespace prefixes (`add-rules-for-mode` -> `electric-operator-add-rules-for-mode` and `prog-mode-rules` -> `electric-operator-prog-mode-rules`).

**Comment by jasonm23** [comment]
Ah, ok then that makes it easier.

We could edit this thread down and add some notes to the wiki (or maybe the README) to help contributors add support for other modes.

BTW The CoffeeScript spacing support looks ok with your settings.

**Comment by davidshepherd7** [comment]
There's already a [customisation](https://github.com/davidshepherd7/electric-operator/blob/master/README.md#customisation) section of the readme, I've added a bit more explanation of how to add new modes, but feel free to send a pull-request if you can see any more improvements.

> BTW The CoffeeScript spacing support looks ok with your settings.

Great, I'll merge it in. Let me know if you find any bugs :+1:

**Comment by jasonm23** [comment]
Will do,  thank you.
