### ISSUE TITLE
Problems with new-mode

### ISSUE THREAD

**Issue by arnyeinstein** [davidshepherd7/electric-operator#13]
Hi David
I tried the following:

(apply #'electric-operator-add-rules-for-mode 'gams-mode
       electric-operator-prog-mode-rules)
(add-hook 'gams-mode-hook #'electric-operator-mode)
(add-hook 'ess-mode-hook #'electric-operator-mode)

.emacs comiles correctly, but when restarting I get this error:
Warning (initialization): An error occurred while loading `c:/emacs/home/.emacs.elc':

Symbol's value as variable is void: electric-operator-prog-mode-rules

Any idea what I am doing wrong?

Renger

**Comment by davidshepherd7** [comment]
Hmm, that's strange. Are you sure that electric operator is loaded before this point? If not try adding `(require 'electric-operator)` before the `apply` (or, a bit more advanced but my preferred method: use [`use-package`](https://github.com/jwiegley/use-package) to deal with loading).

**Comment by arnyeinstein** [comment]
that was the problem. Sorry...
Great package to keep my files nicely coded!

**Comment by davidshepherd7** [comment]
No problem, glad it was so easy to fix :)
