### ISSUE TITLE
gams-mode support?

### ISSUE THREAD

**Issue by davidshepherd7** [davidshepherd7/electric-operator#14]
Continued from [here](https://github.com/milkypostman/melpa/pull/2870#issuecomment-118278167)

**Comment by arnyeinstein** [comment]
It works like a dream!

**Comment by arnyeinstein** [comment]
I have a written a blog post http://blog.modelworks.ch/, so perhaps you will get more people as enthusiastic as I am

**Comment by davidshepherd7** [comment]
Oh wow, thanks! :)
