### ISSUE TITLE
Comma is not spaced correctly in ess-mode

### ISSUE THREAD

**Issue by davidshepherd7** [davidshepherd7/electric-operator#17]
@xin-jin said:
> Hey, I find that under ess-mode, "," does not yield ", ". Do you have any idea why? `(cons "," ", ")` does not work (but `(cons "." ". ")` will turn "." to ". ", so I think it is special for `,`).

**Comment by davidshepherd7** [comment]
I found this in my `ess-mode` config:

```
  ;; ess-mode tries to do some stupid stuff with ',',
  ;; disable this.
  (define-key ess-mode-map (kbd ",") nil)
```

The function `,` is normally mapped to is `ess-smart-comma`:

```
If comma is invoked at the process marker of an ESS inferior
buffer, request and execute a command from `ess-handy-commands'
list.
```

if you don't need that you can just add the above line to your config.

If you do need that then you could try `ess-mode`'s own smart operator spacing (only implemented for `,` currently) using the variable `ess-R-smart-operators`.

I'll talk to the `ess-mode` maintainers about possible long-term fixes.

**Comment by davidshepherd7** [comment]
Ok, I've pushed a fix which *should* make it work without any additional configuration.

Unfortunately I'm not currently able to integration-test ess-mode because ess-mode isn't included in default Emacs. I'll look into it...

**Comment by xin-jin** [comment]
Thanks!
