### ISSUE TITLE
customization question

### ISSUE THREAD

**Issue by fkgruber** [davidshepherd7/electric-operator#18]
Hi
In R a common commands have the following form: %in% and %>%. Is it possible to customize electric-operator to handle this type of expression as operators rather than separate % from in and % from >?

Fred

**Comment by davidshepherd7** [comment]
Absolutely, it's explained [here](https://github.com/davidshepherd7/electric-operator#customisation).

For those particular cases, to add a single space on both sides you would use:

    (electric-operator-add-rules-for-mode 'ess-mode
      (cons "%>%" " %>% ")
      (cons "%in%" " %in% "))

(this code goes in `.emacs` somewhere after `(require 'electric-operator)`). You can add any other operator you can come up with in the same way.

Are these standard R operators? If you can give me a list of all such operators then I'll add them to the default rules list.

**Comment by davidshepherd7** [comment]
I found a list of such operators and added them to the default rules for R. Let me know how they work out.

@xin-jin: could you give these a try as well sometime?

**Comment by xin-jin** [comment]
Yea, thanks. I think they could be useful to some people, though I myself uses yasnippet to input those operators, which already takes care of the space. I did try it. The rules you added work as expected, and it doesn't conflict with yasnippet.

**Comment by davidshepherd7** [comment]
Great, thanks :+1:

**Comment by fkgruber** [comment]
I tried it and works great. Thanks a lot
