### ISSUE TITLE
Incorrect spacing for `*` after `)` in Python.

### ISSUE THREAD

**Issue by lkilcher** [davidshepherd7/electric-operator#19]
I'm getting this strange behavior if I type a `*` after a `)`, electric-operator forces no spacing around the `*`. For example, when I type:

    np.ones(3)*7

I would expect electric operator to snap this to:

    np.ones(3) * 7

But it just stays as above. To make this worse, I can't even correct the issue by trying to insert spaces. For example, if I move my cursor to where the `|` is here:

    np.ones(3)*|7

And hit `spacebar`, nothing happens! I can insert a space before the `*`, but if I then try to insert a space after it again, the whole line snaps back to the original case.  In order to insert the correct spaces, I've had to do manually insert a dummy character, e.g. `a`:

    np.ones(3) *a 7

Then go back and delete the `a`.  Anyone else having this issue?

**Comment by davidshepherd7** [comment]
I'll look into it soon, but for now you should be able to work around it by quoting (with C-q) the * and maybe the following space.

**Comment by davidshepherd7** [comment]
Yep, I made a mistake with a regex in the `*args` handling. Should be fixed now, thanks for reporting it :+1: .

**Comment by lkilcher** [comment]
Got it. It works perfectly. Thanks for the quick response!
