### ISSUE TITLE
Multiplication by a pointer dereference is interpreted as a pointer to pointer

### ISSUE THREAD

**Issue by Dickby** [davidshepherd7/electric-operator#22]
I found two problems with the handling of pointers in c-mode:

1. In the definition of a pointer to a struct spaces are inserted.
example:
`struct s * foo;`
instead of
`struct s *foo`
you can't use `looking-back` for a struct keyword because it could be a typedef.
my suggestion is `looking-back` for an equals sign. If there is no equals sign, it should be the definition of a pointer.( I'm not totally shure) 

2. wrong spacing if a dereferenced pointer is used on the right side of an equation (not directly after equals sign).
example:
`result = foo **bar`
instead of
`result = foo * *bar;`
if it is a division it will be  the beginning of a c comment.

**Comment by davidshepherd7** [comment]
The first bug is closely related to #11, and unfortunately I don't really know how to fix it. You can have pointer derefs without an `=`, for example in `*a++`. To get it completely correct we probably need a C/C++ parser! At the moment things ending in `_t` are treated as types, and so pointers to them should work. I'll try checking for the struct keyword as well.

The second one might be fixable, at least for common cases. I'll have a go.

**Comment by davidshepherd7** [comment]
The first bug should be fixed for non-typedef'd structs (and unions, enums). I think that's all that can be done at the moment.

Fixing the second bug will require changing the internals of electric-operator (whitespace between operator characters is currently ignored), but I might be able to get it fixed at some point.

**Comment by davidshepherd7** [comment]
That might be a fix for 2., let me know if you come up with examples where it doesn't work.

The fix will actually make support for pointer-to-pointer types slightly worse unfortunately, because it now depends on the same type-detection heuristic as the normal pointer types.

**Comment by Dickby** [comment]
maybe I'm wrong, but one or more `*` at the beginning of a line should always be a pointer.

**Comment by davidshepherd7** [comment]
Not necessarily, you could have  something like

    result = (a_long_maths_expression)
        * (another_long_maths_expression);

**Comment by Dickby** [comment]
So looking for a new line is not working, but isn't it possible to look back for `;` or `,` as an indicator for a new c-statement?

**Comment by davidshepherd7** [comment]
Yeah I'm checking something like that at the moment (with lots of other things like `(` and `[`) in `probabaly-unary-operator?`. In fact it looks like I do look for 'beginning of line' as well!

I think distinguishing between pointer-dereference and multiply is pretty good at the moment though, unless you've come across some places where it fails?

**Comment by davidshepherd7** [comment]
I'll close this issue now because the only thing remaining unfixed is the same as #11.

Let me know if you have any problems with the multiplication by pointer-deref fix, or if you find any cases where pointer-types could be detected but aren't.
