### ISSUE TITLE
Handle operators for ess-mode

### ISSUE THREAD

**Issue by davidshepherd7** [davidshepherd7/electric-operator#3]

**Comment by davidshepherd7** [comment]
I've added a rule for `<-` to ` <- ` and to ignore `.`.

Are there any other operators that R uses that are different to other languages?

Does anyone use ess-mode for anything but R?

**Comment by xin-jin** [comment]
Thanks! Actually you don't need the rules for `<-`. It's already in ess-mode. Could `+,-,*,/` also be disabled by default?

I guess some people also use it for julia. I only use R though.

**Comment by davidshepherd7** [comment]
Oh I forgot it does ´<-´, if it causes problems let me know and I'll remove it, otherwise I'll just leave it for now.

I'll leave the `+-*/` as they are by default for consistency, it's easy enough to change if you prefer no to space them.

Well, hopefully no one will use it for Julia! That would be a nightmare to implement since they use the same major mode name...

**Comment by xin-jin** [comment]
Hey, I find that under ess-mode, `,` does not yield `,_`. Do you have any idea why? `(cons "," ", ")` does not work (but  (cons "." ". ") will turn `.` to `._`, so I think it is special for `,`).

**Comment by davidshepherd7** [comment]
Hi, I opened a new issue for this [here](https://github.com/davidshepherd7/electric-operator/issues/17) to make it easier for anyone searching in the future.
