### ISSUE TITLE
is there a way disable electric operator for function arguments?

### ISSUE THREAD

**Issue by fkgruber** [davidshepherd7/electric-operator#34]
so for example
somefunc(a=1, b=2)

thanks
Fred

**Comment by davidshepherd7** [comment]
Yep, that example is already implemented for python. What language(s) do you want it for? Is it only `=` that should be unspaced inside function calls?

**Comment by fkgruber** [comment]
Hi 
I need it for R.

Yes that would only be for =. It is part of some R coding guidelines
ex 
https://www.bioconductor.org/developers/how-to/coding-style/

thanks
Fred

**Comment by davidshepherd7** [comment]
Yeah should be easy. Are there any cases where there could be an `=` inside some brackets that should have spaces around it?

**Comment by davidshepherd7** [comment]
That should work for the example you gave. Let me know if you find any edge cases where it doesn't work as expected.

Thanks for reporting it :+1:

**Comment by fkgruber** [comment]
Thanks
I can't think of a situation where you would have an = inside a bracket right now.

Fred

**Comment by fkgruber** [comment]
I just tried the new build and works great.
thanks a lot

**Comment by jabranham** [comment]
Hi - 

As @davidshepherd7 mentioned, this is only the suggested behavior in _some_ style guides. For example, both google's and Hadley Wickham's style guides suggest putting spaces around the equals sign in function calls. Is there a way to re-enable this behavior?

Thanks!

**Comment by davidshepherd7** [comment]
Ah damn, that makes life more complicated. An easy temporary fix is to override the new behaviour and put spaces around `=` everywhere:

    (electric-operator-add-rules-for-mode 'ess-mode (cons "=" " = "))

I guess at some point I'll add a custom variable so that people can easily get whichever form they prefer.

**Comment by davidshepherd7** [comment]
Ok I've added a customize option for this. The default behaviour is to again add spaces around `=` even for function named arguments.

@fkgruber You should set `electric-operator-R-named-argument-style` to `'unspaced` to get the behaviour you prefer.

**Comment by fkgruber** [comment]
sounds good. 
thanks
