### ISSUE TITLE
Python ":" Bug

### ISSUE THREAD

**Issue by gopar** [davidshepherd7/electric-operator#40]
So basically it works most of the time but when I do something like the following:

```python
sorted([], key=lambda x:x)
```
I can't put a space after the colon which is a pep8 best practice for Python.  It's suppose to be like this:

```python
sorted([], key=lambda x: x)
```
Any suggestions? Or is there something I'm missing?

Thanks!

**Comment by davidshepherd7** [comment]
No that looks like a bug, I'll look into it.

Thanks for reporting it :+1:.

**Comment by gopar** [comment]
Oh snaps! Yeah you're right. I honestly don't know why I put "wrong" instead of "bug". Dang, what's up with me. Makes it sound like it's horrible, my apologies.

Thanks for the package! I find it amazing :D

**Comment by davidshepherd7** [comment]
Oh no I didn't mean anything like that! The "no" was in response to your "Or is there something I'm missing?" :)

Anyway if you pull the latest version (or update in a few hours once melpa builds it) it should be fixed. There's an [edge case](https://github.com/davidshepherd7/electric-operator#complex-default-arguments-in-python-lambdas) which still won't quite work, but I don't think it will be a real life problem.

**Comment by gopar** [comment]
Right on \o/

Thanks for the fix! :D
