### ISSUE TITLE
more rules for PHP

### ISSUE THREAD

**Issue by abrochard** [davidshepherd7/electric-operator#42]
Hi, 
I really like this mode, use it all the time for PHP in php-mode. But some rules are missing.
Here are the ones I have in my config. Maybe you would like to add them as default?
```
  (electric-operator-add-rules-for-mode 'php-mode
                                        (cons " - >" "->"))
  (electric-operator-add-rules-for-mode 'php-mode
                                        (cons " / /" "// "))
  (electric-operator-add-rules-for-mode 'php-mode
                                        (cons " = > " " => "))
  (electric-operator-add-rules-for-mode 'php-mode
                                        (cons " < ?" "<?"))
```
Thanks!

**Comment by davidshepherd7** [comment]
Hi,

thanks for the suggestions, I've added them to the defaults. Let me know if you find any other PHP specific stuff that's missing, I've never written any PHP and IIRC I just added the operators on the w3schools page.

:+1:

**Comment by abrochard** [comment]
Awesome! Thank you. I will let you know if I come across anything else.
