### ISSUE TITLE
Haskell-mode: prefix notation is not supported

### ISSUE THREAD

**Issue by CSRaghunandan** [davidshepherd7/electric-operator#43]
pretty sure this can be patched up easily. But, i guess since electric operator works for '=' , it makes it impossible to use the '=>' operator unless the `electric-operator-mode` is  turned off. 
Is there a way we can somehow add an exception rule to '=' that also checks the next character inserted (if '>' is the next character inserted, insert ' => ' and if any other character is pressed insert ' = a' [a is any other character])?

**Comment by davidshepherd7** [comment]
Yep we can do that easily. For now you can just add a rule `(cons "=>" " => ")` for haskell mode (details in the readme). I'll add the rule to the defaults when I get a chance.

Thanks for letting me know :+1:

**Comment by davidshepherd7** [comment]
Should be fixed by fc5c139785fd1d73a8f9183d0055cf005cfb5f0f. Let me know if it isn't.

Also I just thought of another possible issue: in Haskell you can write things like

    foo = >

to declare that `foo` is the greater than operator function, right? But currently electric operator won't recognise that as being different to `foo :: Eq a =>`. You can work around that by doing a quoted insert of > (with `C-q >`), but if it's a reasonably common occurrence we might be able to fix it by checking something similar to `cc-mode`'s `c-guess-basic-syntax` if that exists in `haskell-mode`.

**Comment by CSRaghunandan** [comment]
Problem fixed 👍 
Thanks for the very quick response. Much appreciated.

**Comment by CSRaghunandan** [comment]
Okay, there seems to be another minor quirk for haskell.  The`.` operator should be excluded by default for haskell-mode. Otherwise, it would be impossible to use list comprehensions like `[1..10]` and import statements.

**Comment by davidshepherd7** [comment]
I think we can do better than just disabling it, we can have a separate rule for `..` which doesn't have spaces around it:  `(cons ".." "..")`. That way `f . g` still works. I'll add one later.

I guess you are the first person to use this for real haskell development, so keep reporting any problems you come across :+1:

**Comment by CSRaghunandan** [comment]
I'll report if I come across any problems. 👍  I'm very new to haskell and god I love it. Such a neatly designed language.
I'll keep reporting bugs in this thread or should I make a new thread each time ?

**Comment by CSRaghunandan** [comment]
Hi, sorry I couldn't test the new commit before, but the original problem is still there, i.e. I can't use the `.` operator on things like import statements (like `import Data.List`). I'm not sure if you can do this, but given how hackable lisp is, is it possible to exclude electric operator on `.` only when used as a `name qualifier` (i.e like in import statements) and not when using it as a function composition operator (like in `f . g`).

Also, the comment delimiter `--` can be made to work as `-- ` instead of ` -- `. Same for `;`, it can be expanded as `; `

Also, I should be able to enter things like `(+), (-) or (> 3) (3 >)`, etc.. and electric operator needs to disabled inside only some operations when inside parenthesis.  Sometimes we may need to enter things like `(a -> b -> a) -> a -> a`. 
Maybe we can exclude electric operator when cursor is *only inside* a pair of parenthesis like so `(|)` and  when cursor is positioned anywhere else inside a parenthesis like `(a |)`, electric operator should work as before.

here are some operators that need to be included for electric operator mode:- 
- `~` 
- `>>`
- `>>=`
- `<*>`
- `<$>`
- `{-`
- `-}`

**Comment by davidshepherd7** [comment]
> Also should I keep reporting bugs in this thread or make a new thread each time?

Can you report any unrelated future ones in a separate thread? But we'll keep the discussion about these bugs in this thread since we've started.

> Hi, sorry I couldn't test the new commit before, but the original problem is still there, i.e. I can't use the . operator on things like import statements (like import Data.List).

Ah, I missed this when I read your issue the first time. Yeah I think `.` will need to be disabled unfortunately. We could handle `import Data.list` by just searching for `^import`, but I don't think theres any way to distinguish between qualified function calls and function composition.

> Also, the comment delimiter -- can be made to work as '-- ' instead of ' -- '. Same for ;, it can be expanded as '; '

Sorry I don't really understand what you mean the rule for `--` currently expands to have a single space after it (I think...) and there's no rule for `;`.

> Also, I should be able to enter things like (+), (-) or (> 3) (3 >), etc.. and electric operator needs to disabled inside only some operations when inside parenthesis. Sometimes we may need to enter things like (a -> b -> a) -> a -> a.
Maybe we can exclude electric operator when cursor is only inside a pair of parenthesis like so (|) and when cursor is positioned anywhere else inside a parenthesis like (a |), electric operator should work as before. This is very crucial, otherwise it's impossible to use it for haskell-mode.

Hah yeah, this is going to be interesting. I'm about half way through an implementation that should work but I'll probably need to do some general refactoring to make the code sane.

I've added rules for all the operators (`~`, `-}` get spaces before, `{-` gets a space after and the rest get a space either side).

**Comment by CSRaghunandan** [comment]
> Sorry I don't really understand what you mean the rule for -- currently expands to have a single space after it (I think...) and there's no rule for ;.

`--` currently expands with spaces on either side. `;` is sometimes used to delimit statements within a `let` expression, might be useful to have a space after it. Just minor quirks, but could help improve overall experience.


Thank you for the quick work. It'll be perfect for haskell usage after the parenthesis problem is fixed 👍

**Comment by CSRaghunandan** [comment]
looks like `--` expands as intended in haskell-mode. Sorry, my bad.

**Comment by davidshepherd7** [comment]
I've added partial support for prefix operators in [this branch](https://github.com/davidshepherd7/electric-operator/tree/action-lists), could you give it a try sometime please? At the moment it handles stuff like `(+ 1)` and `1 + 1` but not `(+)`, that will require some more fiddling with the core code.

**Comment by CSRaghunandan** [comment]
Tried it out and it works for `(+ 3)`, but entering the operator after the digit/variable expands like so `(3 + )`. This is a step forward 👍 Thanks for the effort

**Comment by davidshepherd7** [comment]
Ah, yeah I forgot you can do `(3 +)` that's going to be tricky as well...

**Comment by davidshepherd7** [comment]
Right, think I've got it now! GIve the same branch a try: it should work for all the cases you've mentioned so far :smile:.

Also if you could use that branch for any programming you do in the next week or two, and report any issues that would be great. I had to make some fairly fundamental changes so I'm a little worried about breakages, there's plenty of tests but still...

**Comment by CSRaghunandan** [comment]
Hmm just a question before I try this out, what is the correct way to get electric-operator.el from the test branch ? 

I presume I should copy the file and replace the one found in my `.emacs.d/elpa/electric-operator-(version number here)` and byte compile the new file?

**Comment by davidshepherd7** [comment]
I would usually clone the repository, checkout the branch, and add the
directory to `load-path` (oh, and delete the melpa version). That way it's
easy to switch versions to send patches (if you like).

But your way will work fine as well.

**Comment by CSRaghunandan** [comment]
I replaced the new file from the branch and `byte-compiled` the file and I got a bunch of warnings and when I test in `haskell-mode` I get the same problem as my previous post.

> Tried it out and it works for (+ 3), but entering the operator after the digit/variable expands like so (3 + ). This is a step forward 👍 Thanks for the effort

**Comment by davidshepherd7** [comment]
The warnings are about obsolete functions right? Those are functions from
electric-operator that I've (just) declared obsolete. I don't know why
emacs warns about that when you do a manual byte compile...

I forgot to mention, but you'll need to reload electric-operator from the
new file (either using `eval-buffer` or `load-library` ) or restart emacs
after you replace it.

**Comment by davidshepherd7** [comment]
Just pushed another fix which *should* also support electric-pair style typing, where you type `()` then add the contents inside the parens.

**Comment by CSRaghunandan** [comment]
Sorry I couldn't try it yesterday, was pretty late here.
and yes, they were bunch of warnings about using obsolete functions. But I went ahead and deleted melpa version and manually loading the test branch version using `load`. Guess this is better, I can just replace the old folder and restart emacs.

So far, I can use :- 
`(+)`
`(a +)`
still need support for :- 
`(a + b)` (but can this be done?)
'(+ a)' 

I'm amazed at what elisp is capable of sometimes 👍

**Comment by davidshepherd7** [comment]
Hey, so I thought I'd left a comment when I implemented it but I guess I didn't. I think there should be complelete support for every use-case mentioned so far in the haskell-currying branch (check the tests in the commit reference above if you're interested in exactly what is handled).

Can you try it out please? (yeah, again sorry! Hopefully I'll have caught all the edge cases in the tests now)

**Comment by CSRaghunandan** [comment]
Cool, I'll look into it now and report back

**Comment by CSRaghunandan** [comment]
Hello, sorry I took so long to test them the new branch out. It looks fine so far 👍  All you need to do is add support for other operators and we'd be set :) 
Thanks

**Comment by davidshepherd7** [comment]
No it should work for all of them (I only wrote tests for `+` and a few special cases because it's all the same code).

**Comment by CSRaghunandan** [comment]
Try writing `(-3)` it should expand to `(- 3)` but it's not expanding for me. 
Also `(a-b)` should expand to `(a - b)`, but it expands to `(a -b)`.  A lot of operators doesn't seem to work as they should inside parenthesis, here's some I tested :- `++`, `<=` `==` `>=` or `/=`. It kinda looks like none of the two character operators are working ?? can you please confirm if this is the case ?

**Comment by davidshepherd7** [comment]
Ah yeah I think I disabled `-` because there's no way to distinguish
between minus one in brackets and the function that subtracts 1.

The multi character operators problem sounds wrong though, I'll have a look
at that.

**Comment by CSRaghunandan** [comment]
`/` operator also is not working

**Comment by davidshepherd7** [comment]
So it looks like there are two things going on:

1. It's no longer enough to just eval the new version of `electric-operator.el` (that seems to be what's causing `-` and `/` to break for you).  Probably because something is no longer added to a list, but is still there from the previous version unless you restart emacs.

2. Certain multi-character operators are broken when combined with electric-pair-mode (you're using that right?), but for some reason it works in the tests, which is very strange because ecukes tries hard to be exactly like a real user.

**Comment by CSRaghunandan** [comment]
I didn't eval the new version of `electric-operator.el`. I deleted the MELPA package, put the new haskell branch file into my `load-directory` and required the package in my `init.el` file. Would  this cause a problem ? Or do I need to do something else ?

I do not have `electric-pair-mode` enabled. I use `smartparens-mode`. I tested out after disabling `smartparens-mode` and multiple character operators are working indeed.  So, for `electric-operator-mode` to work properly, I'd need to disable `smartparens-mode` ?

**Comment by CSRaghunandan** [comment]
I guess they also break down when I place my cursor within a parenthesis pair like so : `(|)`.  This is what smartparens did by default, so. 
But that's alright, I can add an exception in `smartparens-mode` to disable pairing of `(` just for haskell mode.

**Comment by davidshepherd7** [comment]
> I didn't eval the new version of electric-operator.el. I deleted the MELPA package, put the new haskell branch file into my load-directory and required the package in my init.el file. Would this cause a problem ? Or do I need to do something else ?

Yeah that should work as long as you restart emacs.

> So, for electric-operator-mode to work properly, I'd need to disable smartparens-mode ?

No, I think I've fixed it now you shouldn't need to disable smartparens. Not being compatible with auto pairing is definitely a bug!

**Comment by CSRaghunandan** [comment]
> No, I think I've fixed it now you shouldn't need to disable smartparens. Not being compatible with auto pairing is definitely a bug!

I don't see any updates to the haskell branch? Have you pushed the fix yet ?

**Comment by davidshepherd7** [comment]
No I didn't quite have time to finish it this morning, pushed now though :) Still not sure why my tests were passing though so proceed with caution...

If you're curious [this](http://emacs.stackexchange.com/questions/27581/why-do-setq-and-set-quote-act-differently-on-let-bound-variables-with-lexical-sc/27584#27584) was the problem. Elisp is crazy sometimes!

**Comment by CSRaghunandan** [comment]
ah i can't quite comprehend what that actual problem was. I know very little elisp,
And I tested it out now and multi-character operators are working fine now 👍  Can you checkout how `/` expands? it's not expanding properly for `(a/b)` and `(/a)`. Other than that, I think most operators are working fine. If i come across any problems i'll report.

**Comment by davidshepherd7** [comment]
Yeah they were being handled wrong, fixed now :+1:

**Comment by CSRaghunandan** [comment]
Checked now and `-` and `/` are fixed 👍  Everything should be working fine now. Thank you so much for investing time into this issue.
Cheers.

**Comment by CSRaghunandan** [comment]
Also, let me know when the haskell-curry branch will be merged with master, so that I can install the package from MELPA and delete the current file that I've in my load directory

**Comment by davidshepherd7** [comment]
Hi, these changes are on melpa stable and unstable now (well, whenever the next melpa build is done, an hour or so probably).

**Comment by CSRaghunandan** [comment]
Yey that calls for a celebration 👍 
thank you.

**Comment by davidshepherd7** [comment]
@CSRaghunandan Are you using the haskell support? Are you happy with it? 

I've had a longer play with haskell since adding this feature and I found it almost unusable. I'm thinking that perhaps whitespace is so important in haskell that it doesn't make sense to insert it automatically.

If it's not really useful then I'd like to remove haskell support because IIRC it alone is responsible for most of the complex special-case stuff in electric-operator.
