### ISSUE TITLE
Add support for js2-mode

### ISSUE THREAD

**Issue by CSRaghunandan** [davidshepherd7/electric-operator#44]
Can you please add support to js2-mode as well, since js-mode is already supported it shouldn't take a lot of work.

**Comment by davidshepherd7** [comment]
It should work already because it derives from `js-mode`, and it seems to work fine for me. Have you tried it out?

**Comment by CSRaghunandan** [comment]
Yes, tried out the rules added for js-mode in electric-operator.el 
None of them are working.  Is something wrong in my side ?

**Comment by davidshepherd7** [comment]
> Yes, tried out the rules added for js-mode in electric-operator.el

What do you mean exactly by that? All you should need to do is put `(add-hook 'js2-mode-hook #'electric-operator-mode)` in your config somewhere and it should just work (or even just `M-x electric-operator-mode`).

If that's not working then it might be something on your end. What version of js2-mode are you using? I'm on 20160826.1908 from melpa unstable. Try opening the help for `js2-mode` (i.e. `M-x describe-function RET js2-mode`) and checking what the parent mode is, it should be `js-mode`.

**Comment by CSRaghunandan** [comment]
Yes, I've done the same. Added electric-operator-mode to js2-mode-hook. And I'm using the same js2-mode version as the one you mentioned. And as expected, js-mode is indeed the parent of js2-mode.. 

>> Yes, tried out the rules added for js-mode in electric-operator.el

> What do you mean exactly by that?

I tried out some of the operators from here :- 

```
(add-rules-for-mode 'js-mode
                    (cons "%=" " %= ")
                    (cons "++" "++ ")
                    (cons "--" "-- ")
                    (cons "===" " === ")
                    (cons "!==" " !== ")
                    (cons "<<" " << ")
                    (cons ">>" " >> ")
                    (cons ":" #'js-mode-:)
                    (cons "?" " ? ")
                    (cons "/" #'js-mode-/)
                    (cons "//" "// ")
                    (cons "/*" "/* ")
                    (cons "=>" " => ") ; ES6 arrow functions
                    )
```

**Comment by davidshepherd7** [comment]
Hmm, that's strange, some more possibly useful questions:

* Does it work in js-mode?
* What version of emacs are you using (not that it should matter..)? 
* Do you get any errors? 
* Is electric-operator-mode definitely enabled?
* If you eval `(electric-operator-get-rules-for-mode 'js2-mode)` what does it return?

BTW to run that code outside of the namespace you'll need to add the prefix `electric-operator-` to `add-rules-for-mode`, but apart from that it should work.

**Comment by CSRaghunandan** [comment]
> Does it work in js-mode?
Works fine in js-mode.

> What version of emacs are you using (not that it should matter..)?
Emacs 25.1 pretest RC2.

> Do you get any errors?
Nope, not getting any erros.

> Is electric-operator-mode definitely enabled?
Yup. 

> If you eval (electric-operator-get-rules-for-mode 'js2-mode) what does it return?
`nil` ! This is strange.. I guess this is where the problem is. How can I fix this ?

**Comment by davidshepherd7** [comment]
So, looks like I'm an idiot! I thought it was working because it loaded the rules for prog-mode.

I'll add it support now :+1:

**Comment by CSRaghunandan** [comment]
no problem. 
Thanks for the quick responses 👍

**Comment by davidshepherd7** [comment]
Basic support is added.

The final forward slash of a regex is not working the the moment because of an oddity in the way js2-mode treats regex literals, see #45.
