### ISSUE TITLE
Put an Undo Boundary Around Operator 

### ISSUE THREAD

**Issue by ErikKnowles** [davidshepherd7/electric-operator#51]
Some of the modes I use don't work perfectly with electric-operator, so there are times when I'd like to undo the whitespace expansion. As it stands, doing an "undo" undoes the expansion plus some amount of typing before the expansion (back to the last undo boundary). It'd be nice to add an (undo-boundary) call right before (delete-region...) in "post-self-insert-function".

Hooks before and after expansion would also work, but seem like overkill.

**Comment by ErikKnowles** [comment]
Just to clarify, the (undo-boundary) would allow me to undo the effects of the electric-operator expansion without undoing anything before that point.

**Comment by davidshepherd7** [comment]
Yeah that sounds like a good idea, I'll try to look into it at some point :+1:

**Comment by davidshepherd7** [comment]
Done, it works really nicely thanks for the idea.
