### ISSUE TITLE
Julia mode

### ISSUE THREAD

**Issue by honghuzi** [davidshepherd7/electric-operator#53]
Please add Julia mode support

**Comment by davidshepherd7** [comment]
For my future reference: https://docs.julialang.org/en/release-0.4/manual/mathematical-operations/

**Comment by davidshepherd7** [comment]
Ok I've implemented everything I can understand from the operator precedence section of that page.

Do you know what the `: ..` operator that it mentions is? How about `<:`?

I've never used Julia so if there are any edge cases let me know.

**Comment by honghuzi** [comment]
Please keep up with the latest version https://docs.julialang.org/en/latest/. The doc reads:

1.  `:..` create a Symbol by concatenating the string representations of the arguments
  together.
2. `<:` is a function. `T1 <: T2` returns true if and only if all values of type T1 are also
  of type T2.

**Comment by davidshepherd7** [comment]
They should all be done, let me know if anything doesn't work as expected :+1:
