### ISSUE TITLE
Pre-in/decrement doesn't work correcty when c-electric-state is off

### ISSUE THREAD

**Issue by rcj** [davidshepherd7/electric-operator#59]
When inserting a in-/decrement operator as the first thing on a line, the indentation is incorrect due to the added space from inserting the first and second +/-. In case c-electric-state is turned on it will fix the indentation and it works as intended. If it is turned off however, we end up with an additional indentation of two spaces.

The second space can be fixed by checking in c-mode-++ if there is only whitespace in front of the operator and don't insert the leading space in that case. The first space however cannot be fixed, as it was inserted by the first +/- and is now part of the pre-whitespace.

This could be fixed by checking the indentation after an operator was applied and re-indenting the  line, however, that would break if someone intentionally added leading white-space.

Another option would be to extend operators with e.g. an :after function which is run after the operator was inserted and pre-whitespace restored. For c-mode-++ this function would check if we have one additional space and remove it. However, this would require to change or extend the current rule notation. I would suggest allowing the current cons notation for simple rules and additionally allow to specify a plist with the keywords supported by compiled-rules which could be used for rules that require more options.

What are your thoughts on this? I have a change for this, however, wanted to discuss this with you first before I change/add the rule notation.

**Comment by rcj** [comment]
Actually fixing prefix +/- should fix this without the need to extend the rule notation and needs to be done anyway, however, this will probably eventually be necessary so your opinion on this would be appreciated.

**Comment by davidshepherd7** [comment]
I haven't really thought about it properly yet, but I think we could fix it
by just never adding any prefix whitespace if the operator is the first
thing on the line. I can't immediately think of any cases where you would
want to add non-indentation whitespace as the first thing on the line.

**Comment by rcj** [comment]
int foo = someVal_1 + ... + someVal_n // reaches line length limit
               + someVal_m;

And there are a few other cases.

**Comment by davidshepherd7** [comment]
I would say that's indentation though, certainly autoindenters usually
handle it how I want them to so it's not something I would want to tackle
here.

**Comment by rcj** [comment]
Ah sorry, I probably misunderstood what you meant. I agree that indentation should be handled other tools. Not messing with the current indentation is probably the best approach. My question above was more in the direction of potentially adding e.g. after functions or similar things to rules, not necessarily for indentation but in general as it might be necessary to do some clean-up in certain cases when handling '<', '>' for templates and similar things.
