### ISSUE TITLE
spaces inside <> while including <bits/stdc++.h> causes compiler error.

### ISSUE THREAD

**Issue by BarnikRay** [davidshepherd7/electric-operator#64]
The spaces around / and the double space after . is causing a compiler error. Please fix this issue as this library is used extensively by competitive programmers, so manually removing the spaces each time is annoying.

**Comment by davidshepherd7** [comment]
Hi, what mode are you using? In `c++-mode` I get `#include <bits/stdc++ .h>` (so yeah the `++` needs fixing, for some reason emacs doesn't count those `#includes` as strings). 

I'd expect what you're seeing if you were using plain `prog-mode` or something else not derived from `c-mode`.

**Comment by davidshepherd7** [comment]
The `++` should be fixed now.

**Comment by BarnikRay** [comment]
Thanks.. the issue is fixed.. Previously I had electric-spacing installed instead of electric-operator... My bad I didn't check..
