### ISSUE TITLE
Started Failing on Emacs 26/Current electric-operator

### ISSUE THREAD

**Issue by ErikKnowles** [davidshepherd7/electric-operator#67]
Just installed Emacs 26 and electric-operator from melpa. In any mode descending from progmode triggers the following error on an operator keypress (e.g., "=")

`Debugger entered--Lisp error: (wrong-type-argument compiled-rule ("=" . " = "))
  signal(wrong-type-argument (compiled-rule ("=" . " = ")))
  (or (and (memq (type-of rule) cl-struct-compiled-rule-tags) t) (signal 'wrong-type-argument (list 'compiled-rule rule)))
  (progn (or (and (memq (type-of rule) cl-struct-compiled-rule-tags) t) (signal 'wrong-type-argument (list 'compiled-rule rule))) (aref rule 2))
  (electric-operator-looking-back-locally (progn (or (and (memq (type-of rule) cl-struct-compiled-rule-tags) t) (signal 'wrong-type-argument (list 'compiled-rule rule))) (aref rule 2)))
  (closure ((it ("=" . " = ") ("<") (">") ("%" . " % ") ("+" . " + ") ("-" . electric-operator-prog-mode--) ("*" . electric-operator-c-mode-*) ("/" . electric-operator-c-mode-/) ("&" . electric-operator-c-mode-&) ("|" . " | ") ("?" . " ? ") ("," . ", ") ("^" . " ^ ") ("==" . " == ") ("!=" . " != ") ("<=" . " <= ") (">=" . " >= ") ("*=" . " *= ") ("+=" . " += ") ("/=" . " /= ") ("-=" . " -= ") ("&&" . electric-operator-c++-mode-&&) ("||" . " || ") ("->" . electric-operator-c++-mode-->) (":" . electric-operator-c++-mode-:) ("**" . electric-operator-c-mode-**) ("++" . electric-operator-c-mode-++) ("--" . electric-operator-c-mode---) ("<<" . " << ") (">>" . electric-operator-c++-mode->>) ("/*" . "/* ") ("//" . "// ") ("++;" . "++;") ("--;" . "--;") ("%=" . " %= ") ("^=" . " ^= ") ("&=" . " &= ") ("|=" . " |= ") ("<<=" . " <<= ") (">>=" . " >>= ") ("::" . "::") ("operator=") ("operator<") ("operator>") ("operator%") ("operator+") ("operator-") ("operator*") ("operator/") ("operator&") ("operator|") ("operator?") ("operator,") ("operator^") ("operator==") ("operator!=") ("operator<=") ("operator>=") ("operator*=") ("operator+=") ("operator/=") ("operator-=") ("operator&&") ("operator||") ("operator->") ("operator:") ("operator**") ("operator++") ("operator--") ("operator<<") ("operator>>") ("operator/*") ("operator//") ("operator++;") ("operator--;") ("operator%=") ("operator^=") ("operator&=") ("operator|=") ("operator<<=") ("operator>>=") ("operator::")) (rule-list ("=" . " = ") ("<") (">") ("%" . " % ") ("+" . " + ") ("-" . electric-operator-prog-mode--) ("*" . electric-operator-c-mode-*) ("/" . electric-operator-c-mode-/) ("&" . electric-operator-c-mode-&) ("|" . " | ") ("?" . " ? ") ("," . ", ") ("^" . " ^ ") ("==" . " == ") ("!=" . " != ") ("<=" . " <= ") (">=" . " >= ") ("*=" . " *= ") ("+=" . " += ") ("/=" . " /= ") ("-=" . " -= ") ("&&" . electric-operator-c++-mode-&&) ("||" . " || ") ("->" . electric-operator-c++-mode-->) (":" . electric-operator-c++-mode-:) ("**" . electric-operator-c-mode-**) ("++" . electric-operator-c-mode-++) ("--" . electric-operator-c-mode---) ("<<" . " << ") (">>" . electric-operator-c++-mode->>) ("/*" . "/* ") ("//" . "// ") ("++;" . "++;") ("--;" . "--;") ("%=" . " %= ") ("^=" . " ^= ") ("&=" . " &= ") ("|=" . " |= ") ("<<=" . " <<= ") (">>=" . " >>= ") ("::" . "::") ("operator=") ("operator<") ("operator>") ("operator%") ("operator+") ("operator-") ("operator*") ("operator/") ("operator&") ("operator|") ("operator?") ("operator,") ("operator^") ("operator==") ("operator!=") ("operator<=") ("operator>=") ("operator*=") ("operator+=") ("operator/=") ("operator-=") ("operator&&") ("operator||") ("operator->") ("operator:") ("operator**") ("operator++") ("operator--") ("operator<<") ("operator>>") ("operator/*") ("operator//") ("operator++;") ("operator--;") ("operator%=") ("operator^=") ("operator&=") ("operator|=") ("operator<<=") ("operator>>=") ("operator::")) cl-struct-compiled-rule-tags t) (rule) (electric-operator-looking-back-locally (progn (or (and (memq (type-of rule) cl-struct-compiled-rule-tags) t) (signal 'wrong-type-argument (list 'compiled-rule rule))) (aref rule 2))))(("=" . " = "))
  funcall((closure ((it ("=" . " = ") ("<") (">") ("%" . " % ") ("+" . " + ") ("-" . electric-operator-prog-mode--) ("*" . electric-operator-c-mode-*) ("/" . electric-operator-c-mode-/) ("&" . electric-operator-c-mode-&) ("|" . " | ") ("?" . " ? ") ("," . ", ") ("^" . " ^ ") ("==" . " == ") ("!=" . " != ") ("<=" . " <= ") (">=" . " >= ") ("*=" . " *= ") ("+=" . " += ") ("/=" . " /= ") ("-=" . " -= ") ("&&" . electric-operator-c++-mode-&&) ("||" . " || ") ("->" . electric-operator-c++-mode-->) (":" . electric-operator-c++-mode-:) ("**" . electric-operator-c-mode-**) ("++" . electric-operator-c-mode-++) ("--" . electric-operator-c-mode---) ("<<" . " << ") (">>" . electric-operator-c++-mode->>) ("/*" . "/* ") ("//" . "// ") ("++;" . "++;") ("--;" . "--;") ("%=" . " %= ") ("^=" . " ^= ") ("&=" . " &= ") ("|=" . " |= ") ("<<=" . " <<= ") (">>=" . " >>= ") ("::" . "::") ("operator=") ("operator<") ("operator>") ("operator%") ("operator+") ("operator-") ("operator*") ("operator/") ("operator&") ("operator|") ("operator?") ("operator,") ("operator^") ("operator==") ("operator!=") ("operator<=") ("operator>=") ("operator*=") ("operator+=") ("operator/=") ("operator-=") ("operator&&") ("operator||") ("operator->") ("operator:") ("operator**") ("operator++") ("operator--") ("operator<<") ("operator>>") ("operator/*") ("operator//") ("operator++;") ("operator--;") ("operator%=") ("operator^=") ("operator&=") ("operator|=") ("operator<<=") ("operator>>=") ("operator::")) (rule-list ("=" . " = ") ("<") (">") ("%" . " % ") ("+" . " + ") ("-" . electric-operator-prog-mode--) ("*" . electric-operator-c-mode-*) ("/" . electric-operator-c-mode-/) ("&" . electric-operator-c-mode-&) ("|" . " | ") ("?" . " ? ") ("," . ", ") ("^" . " ^ ") ("==" . " == ") ("!=" . " != ") ("<=" . " <= ") (">=" . " >= ") ("*=" . " *= ") ("+=" . " += ") ("/=" . " /= ") ("-=" . " -= ") ("&&" . electric-operator-c++-mode-&&) ("||" . " || ") ("->" . electric-operator-c++-mode-->) (":" . electric-operator-c++-mode-:) ("**" . electric-operator-c-mode-**) ("++" . electric-operator-c-mode-++) ("--" . electric-operator-c-mode---) ("<<" . " << ") (">>" . electric-operator-c++-mode->>) ("/*" . "/* ") ("//" . "// ") ("++;" . "++;") ("--;" . "--;") ("%=" . " %= ") ("^=" . " ^= ") ("&=" . " &= ") ("|=" . " |= ") ("<<=" . " <<= ") (">>=" . " >>= ") ("::" . "::") ("operator=") ("operator<") ("operator>") ("operator%") ("operator+") ("operator-") ("operator*") ("operator/") ("operator&") ("operator|") ("operator?") ("operator,") ("operator^") ("operator==") ("operator!=") ("operator<=") ("operator>=") ("operator*=") ("operator+=") ("operator/=") ("operator-=") ("operator&&") ("operator||") ("operator->") ("operator:") ("operator**") ("operator++") ("operator--") ("operator<<") ("operator>>") ("operator/*") ("operator//") ("operator++;") ("operator--;") ("operator%=") ("operator^=") ("operator&=") ("operator|=") ("operator<<=") ("operator>>=") ("operator::")) cl-struct-compiled-rule-tags t) (rule) (electric-operator-looking-back-locally (progn (or (and (memq (type-of rule) cl-struct-compiled-rule-tags) t) (signal 'wrong-type-argument (list 'compiled-rule rule))) (aref rule 2)))) ("=" . " = "))
  (if (funcall pred it) (progn (setq result (cons it result))))
  (let ((it (car list))) (if (funcall pred it) (progn (setq result (cons it result)))))
  (while list (let ((it (car list))) (if (funcall pred it) (progn (setq result (cons it result))))) (setq it-index (1+ it-index)) (setq list (cdr list)))
  (let ((list list) (it-index 0)) (while list (let ((it (car list))) (if (funcall pred it) (progn (setq result (cons it result))))) (setq it-index (1+ it-index)) (setq list (cdr list))))
  (let (result) (let ((list list) (it-index 0)) (while list (let ((it (car list))) (if (funcall pred it) (progn (setq result (cons it result))))) (setq it-index (1+ it-index)) (setq list (cdr list)))) (nreverse result))
  -filter((closure ((it ("=" . " = ") ("<") (">") ("%" . " % ") ("+" . " + ") ("-" . electric-operator-prog-mode--) ("*" . electric-operator-c-mode-*) ("/" . electric-operator-c-mode-/) ("&" . electric-operator-c-mode-&) ("|" . " | ") ("?" . " ? ") ("," . ", ") ("^" . " ^ ") ("==" . " == ") ("!=" . " != ") ("<=" . " <= ") (">=" . " >= ") ("*=" . " *= ") ("+=" . " += ") ("/=" . " /= ") ("-=" . " -= ") ("&&" . electric-operator-c++-mode-&&) ("||" . " || ") ("->" . electric-operator-c++-mode-->) (":" . electric-operator-c++-mode-:) ("**" . electric-operator-c-mode-**) ("++" . electric-operator-c-mode-++) ("--" . electric-operator-c-mode---) ("<<" . " << ") (">>" . electric-operator-c++-mode->>) ("/*" . "/* ") ("//" . "// ") ("++;" . "++;") ("--;" . "--;") ("%=" . " %= ") ("^=" . " ^= ") ("&=" . " &= ") ("|=" . " |= ") ("<<=" . " <<= ") (">>=" . " >>= ") ("::" . "::") ("operator=") ("operator<") ("operator>") ("operator%") ("operator+") ("operator-") ("operator*") ("operator/") ("operator&") ("operator|") ("operator?") ("operator,") ("operator^") ("operator==") ("operator!=") ("operator<=") ("operator>=") ("operator*=") ("operator+=") ("operator/=") ("operator-=") ("operator&&") ("operator||") ("operator->") ("operator:") ("operator**") ("operator++") ("operator--") ("operator<<") ("operator>>") ("operator/*") ("operator//") ("operator++;") ("operator--;") ("operator%=") ("operator^=") ("operator&=") ("operator|=") ("operator<<=") ("operator>>=") ("operator::")) (rule-list ("=" . " = ") ("<") (">") ("%" . " % ") ("+" . " + ") ("-" . electric-operator-prog-mode--) ("*" . electric-operator-c-mode-*) ("/" . electric-operator-c-mode-/) ("&" . electric-operator-c-mode-&) ("|" . " | ") ("?" . " ? ") ("," . ", ") ("^" . " ^ ") ("==" . " == ") ("!=" . " != ") ("<=" . " <= ") (">=" . " >= ") ("*=" . " *= ") ("+=" . " += ") ("/=" . " /= ") ("-=" . " -= ") ("&&" . electric-operator-c++-mode-&&) ("||" . " || ") ("->" . electric-operator-c++-mode-->) (":" . electric-operator-c++-mode-:) ("**" . electric-operator-c-mode-**) ("++" . electric-operator-c-mode-++) ("--" . electric-operator-c-mode---) ("<<" . " << ") (">>" . electric-operator-c++-mode->>) ("/*" . "/* ") ("//" . "// ") ("++;" . "++;") ("--;" . "--;") ("%=" . " %= ") ("^=" . " ^= ") ("&=" . " &= ") ("|=" . " |= ") ("<<=" . " <<= ") (">>=" . " >>= ") ("::" . "::") ("operator=") ("operator<") ("operator>") ("operator%") ("operator+") ("operator-") ("operator*") ("operator/") ("operator&") ("operator|") ("operator?") ("operator,") ("operator^") ("operator==") ("operator!=") ("operator<=") ("operator>=") ("operator*=") ("operator+=") ("operator/=") ("operator-=") ("operator&&") ("operator||") ("operator->") ("operator:") ("operator**") ("operator++") ("operator--") ("operator<<") ("operator>>") ("operator/*") ("operator//") ("operator++;") ("operator--;") ("operator%=") ("operator^=") ("operator&=") ("operator|=") ("operator<<=") ("operator>>=") ("operator::")) cl-struct-compiled-rule-tags t) (rule) (electric-operator-looking-back-locally (progn (or (and (memq (type-of rule) cl-struct-compiled-rule-tags) t) (signal 'wrong-type-argument (list 'compiled-rule rule))) (aref rule 2)))) (("=" . " = ") ("<") (">") ("%" . " % ") ("+" . " + ") ("-" . electric-operator-prog-mode--) ("*" . electric-operator-c-mode-*) ("/" . electric-operator-c-mode-/) ("&" . electric-operator-c-mode-&) ("|" . " | ") ("?" . " ? ") ("," . ", ") ("^" . " ^ ") ("==" . " == ") ("!=" . " != ") ("<=" . " <= ") (">=" . " >= ") ("*=" . " *= ") ("+=" . " += ") ("/=" . " /= ") ("-=" . " -= ") ("&&" . electric-operator-c++-mode-&&) ("||" . " || ") ("->" . electric-operator-c++-mode-->) (":" . electric-operator-c++-mode-:) ("**" . electric-operator-c-mode-**) ("++" . electric-operator-c-mode-++) ("--" . electric-operator-c-mode---) ("<<" . " << ") (">>" . electric-operator-c++-mode->>) ("/*" . "/* ") ("//" . "// ") ("++;" . "++;") ("--;" . "--;") ("%=" . " %= ") ("^=" . " ^= ") ("&=" . " &= ") ("|=" . " |= ") ("<<=" . " <<= ") (">>=" . " >>= ") ("::" . "::") ("operator=") ("operator<") ("operator>") ("operator%") ("operator+") ("operator-") ("operator*") ("operator/") ("operator&") ("operator|") ("operator?") ("operator,") ("operator^") ("operator==") ("operator!=") ("operator<=") ("operator>=") ("operator*=") ("operator+=") ("operator/=") ("operator-=") ("operator&&") ("operator||") ("operator->") ("operator:") ("operator**") ("operator++") ("operator--") ("operator<<") ("operator>>") ("operator/*") ("operator//") ("operator++;") ("operator--;") ("operator%=") ("operator^=") ("operator&=") ("operator|=") ("operator<<=") ("operator>>=") ("operator::")))
  (let ((it (-filter (function (lambda (rule) (electric-operator-looking-back-locally (progn (or (and (memq (type-of rule) cl-struct-compiled-rule-tags) t) (signal 'wrong-type-argument (list 'compiled-rule rule))) (aref rule 2))))) it))) (let ((it (-sort (function (lambda (p1 p2) (> (length (progn (or (and (memq (type-of p1) cl-struct-compiled-rule-tags) t) (signal 'wrong-type-argument (list 'compiled-rule p1))) (aref p1 1))) (length (progn (or (and (memq (type-of p2) cl-struct-compiled-rule-tags) t) (signal 'wrong-type-argument (list 'compiled-rule p2))) (aref p2 1)))))) it))) (car it)))
  (let ((it rule-list)) (let ((it (-filter (function (lambda (rule) (electric-operator-looking-back-locally (progn (or (and (memq (type-of rule) cl-struct-compiled-rule-tags) t) (signal 'wrong-type-argument (list 'compiled-rule rule))) (aref rule 2))))) it))) (let ((it (-sort (function (lambda (p1 p2) (> (length (progn (or (and (memq (type-of p1) cl-struct-compiled-rule-tags) t) (signal 'wrong-type-argument (list 'compiled-rule p1))) (aref p1 1))) (length (progn (or (and (memq (type-of p2) cl-struct-compiled-rule-tags) t) (signal 'wrong-type-argument (list 'compiled-rule p2))) (aref p2 1)))))) it))) (car it))))
  electric-operator-longest-matching-rule((("=" . " = ") ("<") (">") ("%" . " % ") ("+" . " + ") ("-" . electric-operator-prog-mode--) ("*" . electric-operator-c-mode-*) ("/" . electric-operator-c-mode-/) ("&" . electric-operator-c-mode-&) ("|" . " | ") ("?" . " ? ") ("," . ", ") ("^" . " ^ ") ("==" . " == ") ("!=" . " != ") ("<=" . " <= ") (">=" . " >= ") ("*=" . " *= ") ("+=" . " += ") ("/=" . " /= ") ("-=" . " -= ") ("&&" . electric-operator-c++-mode-&&) ("||" . " || ") ("->" . electric-operator-c++-mode-->) (":" . electric-operator-c++-mode-:) ("**" . electric-operator-c-mode-**) ("++" . electric-operator-c-mode-++) ("--" . electric-operator-c-mode---) ("<<" . " << ") (">>" . electric-operator-c++-mode->>) ("/*" . "/* ") ("//" . "// ") ("++;" . "++;") ("--;" . "--;") ("%=" . " %= ") ("^=" . " ^= ") ("&=" . " &= ") ("|=" . " |= ") ("<<=" . " <<= ") (">>=" . " >>= ") ("::" . "::") ("operator=") ("operator<") ("operator>") ("operator%") ("operator+") ("operator-") ("operator*") ("operator/") ("operator&") ("operator|") ("operator?") ("operator,") ("operator^") ("operator==") ("operator!=") ("operator<=") ("operator>=") ("operator*=") ("operator+=") ("operator/=") ("operator-=") ("operator&&") ("operator||") ("operator->") ("operator:") ("operator**") ("operator++") ("operator--") ("operator<<") ("operator>>") ("operator/*") ("operator//") ("operator++;") ("operator--;") ("operator%=") ("operator^=") ("operator&=") ("operator|=") ("operator<<=") ("operator>>=") ("operator::")))
  (let* ((rule (electric-operator-longest-matching-rule (electric-operator-get-rules-list))) (operator-regex (and rule (progn (or (and (memq (type-of rule) cl-struct-compiled-rule-tags) t) (signal 'wrong-type-argument (list 'compiled-rule rule))) (aref rule 2)))) (action (and rule (progn (or (and (memq (type-of rule) cl-struct-compiled-rule-tags) t) (signal 'wrong-type-argument (list 'compiled-rule rule))) (aref rule 3)))) (operator-just-inserted nil)) (if (and rule action) (progn (electric-operator-looking-back-locally operator-regex t) (save-excursion (goto-char (match-beginning 0)) (looking-at operator-regex)) (let* ((pre-whitespace (match-string 1)) (op-match-beginning (match-beginning 0)) (op-match-end (match-end 0)) (spaced-string (electric-operator-eval-action action op-match-beginning))) (if spaced-string (progn (setq operator-just-inserted t) (undo-boundary) (delete-region op-match-beginning op-match-end) (if (electric-operator-looking-back-locally "^\\s-*") (progn (insert pre-whitespace) (insert (electric-operator--trim-left spaced-string))) (insert spaced-string))))))) (if (derived-mode-p 'haskell-mode) (progn (electric-operator-haskell-mode-fixup-partial-operator-parens operator-just-inserted))))
  (progn (let* ((rule (electric-operator-longest-matching-rule (electric-operator-get-rules-list))) (operator-regex (and rule (progn (or (and (memq (type-of rule) cl-struct-compiled-rule-tags) t) (signal 'wrong-type-argument (list 'compiled-rule rule))) (aref rule 2)))) (action (and rule (progn (or (and (memq (type-of rule) cl-struct-compiled-rule-tags) t) (signal 'wrong-type-argument (list 'compiled-rule rule))) (aref rule 3)))) (operator-just-inserted nil)) (if (and rule action) (progn (electric-operator-looking-back-locally operator-regex t) (save-excursion (goto-char (match-beginning 0)) (looking-at operator-regex)) (let* ((pre-whitespace (match-string 1)) (op-match-beginning (match-beginning 0)) (op-match-end (match-end 0)) (spaced-string (electric-operator-eval-action action op-match-beginning))) (if spaced-string (progn (setq operator-just-inserted t) (undo-boundary) (delete-region op-match-beginning op-match-end) (if (electric-operator-looking-back-locally "^\\s-*") (progn (insert pre-whitespace) (insert (electric-operator--trim-left spaced-string))) (insert spaced-string))))))) (if (derived-mode-p 'haskell-mode) (progn (electric-operator-haskell-mode-fixup-partial-operator-parens operator-just-inserted)))))
  electric-operator-post-self-insert-function()
  self-insert-command(1)
  funcall-interactively(self-insert-command 1)
  call-interactively(self-insert-command nil nil)`

This was in C++ mode but the same happens in any other progmode-descended mode.

**Comment by ErikKnowles** [comment]
No idea as to why, but it's working fine now.

**Comment by davidshepherd7** [comment]
Ah, I think something like that could happen if you updated electric-operator from an older version. It should always be fixed by a restart of emacs.

I'm not sure how upgrading a package updates the values of variables that existed in the old version, but I suspect it would use the old version's value, which would be wrong. I can't see a way to fix that without adding a lot of complexity.

**Comment by ErikKnowles** [comment]
I'd swear I'd restarted and recompiled several times. Just odd.
Anyway, it's working. Thanks for chiming in, and thanks for the very useful extension.
