### ISSUE TITLE
Space after dot in inferior-ess-mode

### ISSUE THREAD

**Issue by jmburgos** [davidshepherd7/electric-operator#82]
Hi David,
I am getting a space after a dot in inferior-ess-mode, which is problematic for a bunch of reasons including that I cannot write decimal numbers.  Strangely, that does not happen in ess-mode.  My setup is simply this: 

(use-package electric-operator
  :commands electric-operator-mode
  :hook
  ((ess-mode ess-mode) . electric-operator-mode)
  ((ess-mode inferior-ess-mode) . electric-operator-mode)
)

I tried to add

(electric-operator-add-rules-for-mode 'inferior-ess-mode (cons "." "."))

and tried also 

(electric-operator-add-rules-for-mode 'inferior-ess-mode (cons "." nil))

but the problem didn't go away.  Do you know what could be the issue?
Many thanks!

Julian

**Comment by davidshepherd7** [comment]
Hmm, if ess inferior doesn't inherit from prog-mode it might be picking up
the full stop rule for documentation. You could try setting
electric-operator-double-space-docs to nil.

**Comment by davidshepherd7** [comment]
Hi, sorry but I can't reproduce your issue even in `emacs -Q` (emacs 26.1, electric-operator 20181123.805, ess 20190118.1516).

Can you please provide your versions of everything and also try to reproduce it in `emacs -Q`?

**Comment by feng-li** [comment]
Same problem if it is enabled for `inferior-python-mode` with `(add-hook 'inferior-python-mode-hook #'electric-operator-mode)`

If I type
```
import numpy as np
```
and then type `np.` will insert a space after the dot ` `

GNU Emacs 26.1 with default `python.el`

**Comment by davidshepherd7** [comment]
@feng-li Try adding this to your configuration:

```
(apply #'electric-operator-add-rules-for-mode 'inferior-python-mode (electric-operator-get-rules-for-mode 'python-mode))
```

if that works for you I'll add it to the default setup. Hopefully I'll be able to do something similar for ess too.

**Comment by feng-li** [comment]
Yes, this did the trick for python.

**Comment by davidshepherd7** [comment]
Ok I've pushed the python change and a hopefully equivalent one for R. The R changes work for me, but it may not work for versions of ess older than mid-2018 when they renamed ess-mode to ess-r-mode (it's very tricky for me to deal with that kind of thing).

@jmburgos Can you give the melpa (unstable) build a try when you get a chance? If it doesn't work feel free to reopen this issue.

Thanks everyone :+1:
