### ISSUE TITLE
Custom := operator not working in ESS-mode

### ISSUE THREAD

**Issue by despresT** [davidshepherd7/electric-operator#84]
I have an issue with a custom electric-operator.
In ESS-mode when I am typing `:=` I want a space before and after (as an operation sign), but in result I have `: = `
This is like the equal sign erase my cutom change and always add a space before and after it.
Here is my config
(use-package electric-operator
  :ensure t
  :config
  (setq electric-operator-R-named-argument-style 'spaced)
  (add-hook 'ess-mode-hook #'electric-operator-mode)
  (add-hook 'c++-mode-hook #'electric-operator-mode)
  (add-hook 'python-mode-hook #'electric-operator-mode))
(electric-operator-add-rules-for-mode 'ess-mode
  (cons ":=" " := "))

It was working on my Linux PC, but not in Windows.

I am on emacs 26.1 with electric-operator-20190226.727 and ess-20190302.1914

**Comment by davidshepherd7** [comment]
Ess have recently renamed the R mode to something like ess-r-mode, is that
your problem?

**Comment by despresT** [comment]
You are right. It was the new name of ess-r-mode.
It works perfectly now.
Thank you.
