### ISSUE TITLE
unable to use electric-operator-add-rules-for-mode in spacemacs

### ISSUE THREAD

**Issue by c02y** [davidshepherd7/electric-operator#85]
I tried to use electric-operator in spacemacs

I put electric-operator in dotspacemacs-additional-packages, and put
~~~
(add-hook 'c-mode-common-hook #'electric-operator-mode)
(electric-operator-add-rules-for-mode
'c-mode
(cons "<>" "<> ")
(cons "<" " < ")
(cons ">" " > ")
(cons ";" "; ")
(cons "++" "++"))
~~~
in dotspacemacs/user-config, but after I start emacs, it says 

~~~
(Spacemacs) Error in dotspacemacs/user-config: Symbol’s function definition is void: electric-operator-add-rules-for-mode
~~~
in *Message* buffer and I am not able to use the operators defined in electric-operator-add-rules-for-mode in c-mode file. electric-operator-mode is enabled and I am able to use built-in operators.

* Emacs version: GNU Emacs 26.2
* electric-operator version: electric-operator-20190226.727

**Comment by davidshepherd7** [comment]
I haven't really used spacemacs, but that sounds like you haven't actually
require'd the package anywhere. Could that be the issue?

**Comment by c02y** [comment]
I post an isses on spacemacs issue page, and someone answered that I should use 
~~~
(with-eval-after-load 'electric-operator-mode
      (electric-operator-add-rules-for-mode
       'c-mode
       (cons "<>" "<> ")
       (cons "<" " < ")
       (cons ">" " > ")
       (cons ";" "; ")
       (cons "++" "++")))
~~~

now the error message is gone:
~~~
(Spacemacs) Error in dotspacemacs/user-config: Symbol’s function definition is void: electric-operator-add-rules-for-mode
~~~

but the operators defined in electric-operator-add-rules-for-mode don't work at all. Don't know why.

Another thing is, I notice that there is no variable like electric-operator-list-rules-for-mode to list all the builin and defined rules for the major mode.

**Comment by davidshepherd7** [comment]
Yeah I think that must be a quirk of spacemacs' module loading system.

> And another thing is, I notice that there is no variable like electric-operator-list-rules-for-mode to list all the builin and defined rules for the major mode. Are you planning to write one?

I think it would be very useful, but I don't have a lot of time at the moment. So probably at some point in the future :slightly_smiling_face:
