### ISSUE TITLE
-replace-first definition is void

### ISSUE THREAD

**Issue by gopar** [davidshepherd7/electric-operator#9]
when I try to enable `electric-operator` I get a 
~~~
Symbols function definition is void: -replace-first
~~~

Any ideas?

**Comment by davidshepherd7** [comment]
Did you install using package.el or by dropping the source file into your load path? If you installed without package.el do you have a recent version of dash?

**Comment by gopar** [comment]
@davidshepherd7 Installed it through package.el. From what I can see, I have the latest dash version. 2.10.0

**Comment by davidshepherd7** [comment]
Ok, that's odd. What's your Emacs version? Can you try byte-compiling `electric-operator.el` and checking for any other errors or warnings?

**Comment by gopar** [comment]
@davidshepherd7 Just byte compiled. Thats the only error I get.

~~~
In end of data:
electric-operator.el:536:1:Warning: the function `-replace-first' is not known
    to be defined.

Compiling no file at Sun Jun 28 12:59:33 2015

~~~

**Comment by davidshepherd7** [comment]
Ah, I think I've found the problem. `-replace-first` is newer than the latest dash in melpa stable. If you install the latest dash from melpa unstable it will work, alternatively you can wait and I'll push a fix as soon as I can (should be less than half an hour).

Sorry about that. My tests didn't catch it because they use melpa unstable for to one annoying dependency.

**Comment by davidshepherd7** [comment]
Or maybe much less than half an hour, it was a very easy fix :)

Thanks for reporting the issue.

**Comment by gopar** [comment]
@davidshepherd7 No problem. Package looks promising and I'm amazed how quickly this was solved! (Fastest issue fix in git history?) :D

**Comment by davidshepherd7** [comment]
Haha, well I was at my computer and not doing anything in particular when I got the email :)

There's one annoying issue to watch out for with the package at the moment: C/C++/Java comments don't get handled properly. I'm hoping to fix it soon but I think it might be tricky to do well.
