### ISSUE TITLE
"&" and "&&" are a little strange in C++.

### ISSUE THREAD

**Issue by ROCKTAKEY** [davidshepherd7/electric-operator#90]
Hi! I'm very grateful for your package.
In C++ file, spacing around `&` and `&&` is a little strange if electric-operator-mode is on.

## Reproducing
In a.cpp:

```
int main (void){

  auto &a;			// 1. this should be "auto& a;"

  int && r = 0;			// 2. this should be "int&& r = 0;"

  int const & b;		// 3. this should be "int const& b;"
  
  return 0;
}
```

Sorry if it's a matter of preference, but I think it has constant generality.
(especially, my position of the word `const` may look strange. It meats the standard.)

Thanks!

## Other useful info

* Emacs version: 26.1
* electric-operator version: version 1.0.0 (MELPA 20190710.858)

**Comment by davidshepherd7** [comment]
Hi there :)

I think some of what you want can be achieved by setting the
`electric-operator-c-pointer-type-style`. Can you try that and let me know
if anything still doesn't work please?

**Comment by ROCKTAKEY** [comment]
I got it. I set `electric-operator-c-pointer-type-style` to `type`. Then:
```
int main(void){

    auto& a;                    // 1. this is fixed, thanks to electric-operator-c-pointer-type-style :)

    int && r = 0;               // 2. this should be "int&& r = 0;"

    int const & b;              // 3. this should be "int const& b;"
    
    return 0;
}
```
Example 2 and 3 should obey `electric-operator-c-pointer-type-style`, too.

**Comment by davidshepherd7** [comment]
Hi, that should be fixed now, try upgrading after the next melpa unstable build finishes (probably a few hours, but tomorrow if you want to be sure).
