### ISSUE TITLE
Only adds spacing when I use indentation command.

### ISSUE THREAD

**Issue by tigerk0430** [davidshepherd7/electric-operator#91]
Hello authors,

Thanks for the providing great package that I need :-)

I just wondering that does it provide manually add spacing option?

I don't want to add spaces while typing but want to add those whenever I use the indentation command after writing codes.

Thanks in advance :-)

**Comment by davidshepherd7** [comment]
Hi, I think this is essentially the same as issue #20. At the moment: no it can only add spacing while you're writing code. I think that the way the package is written would make it quite difficult to add spacing afterwards.

For formatting code after it's been written you could try using a dedicated autoformatter program instead. Most languages have an one these days (e.g. blacken, tsfmt, gofmt, rustfmt).
