### ISSUE TITLE
incorrect formula spacing

### ISSUE THREAD

**Issue by jthaman** [davidshepherd7/electric-operator#95]
In the following R formula, I expected a space after the plus sign. 

`~ . +occupation:treated`

**Comment by davidshepherd7** [comment]
Oh interesting, is the `.` there a variable name or something else?

**Comment by jthaman** [comment]
In an R formula, the dot is shorthand for "all variables". Similarly, ".:." Means all second order interactions, ".*." Means all main effects plus interactions. There's many users for dot.

**Comment by jthaman** [comment]
I suppose I have fixed all my issues :)

```
(use-package electric-operator
  :ensure t
  :hook
  ((ess-mode python-mode) . electric-operator-mode)
  :custom
  (electric-operator-R-named-argument-style 'spaced)
  :config
  (electric-operator-add-rules-for-mode 'ess-r-mode
                                        (cons ".+" " . + ")
                                        (cons ":=" " := ")))
```

**Comment by davidshepherd7** [comment]
Oh great! I'll add those rules to the default config. Thanks :)

Le mer. 19 août 2020 à 17:09, John T Haman <notifications@github.com> a
écrit :

**Comment by davidshepherd7** [comment]
There was actually a bug in a regex which was causing `. + 1` to be spaced incorrectly. That case (and similar cases with other operators than `+`) should work with the next Melpa.

https://github.com/davidshepherd7/electric-operator/commit/1467c5aa235d06b52b6dbc89d2160b3f6d681249

**Comment by jthaman** [comment]
Nice work dude!
