### ISSUE TITLE
incorrect data.table formula

### ISSUE THREAD

**Issue by jthaman** [davidshepherd7/electric-operator#96]
Formulas become malformed in `data.table`. Here's a small example. Suppose I have a data.table with a column I'd like to exponentiate. The data.table syntax is 

```
library(data.table)
DT <- data.table(V1 = rnorm(10))

DT[, V1 := exp(V1)]
```

Electric operator will split up the column from the equal sign like this

```
DT <- data.table(V1 = rnorm(10))

DT[, V1: = exp(V1)]
```

causing an r error.

**Comment by jthaman** [comment]
Sorry for the noise. I think I fixed my issue with

```
(electric-operator-add-rules-for-mode 'ess-r-mode
                                        (cons ":=" " := "))
```

**Comment by jthaman** [comment]
Since I think you might be interested, I've developed a pretty good list of rules that are great help when writing R and Stan code. 

```
  (electric-operator-add-rules-for-mode 'stan-mode
                                        (cons "," ", ")
                                        (cons "~" " ~ "))

  (electric-operator-add-rules-for-mode 'ess-r-mode
                                        (cons ".+" " . + ")
                                        (cons ":" " : ")
                                        (cons "? " "?")
                                        (cons "){" ") {")
                                        (cons "}else{" "} else {")
                                        (cons "for(" "for (")
                                        (cons "if(" "if (")
                                        (cons "while(" "while (")
                                        (cons "::" "::")
                                        (cons ":=" " := ")))

```

**Comment by japhir** [comment]
To expand your nice set, I've added a few to my own config, including the new built-in pipe operator `|>` and made sure that `^` doesn't get space around it (because it [takes high precedence](https://style.tidyverse.org/syntax.html#infix-operators))

**Comment by japhir** [comment]
I think this should still be an issue, as the defaults for R should at least handle base R syntax correctly (new native pipe) and would be nice if it could also handle common other things (such as the walrus operator) by default.

**Comment by davidshepherd7** [comment]
Thanks for the suggestions, I've added the pipe operator and some unit tests based on these.

Some follow up questions:

* Do `:` (and `::`, `:::`) get autospaced with the default configuration? It seems to leave them alone in my unit test and I don't see any configuration that I expect to affect it. See https://github.com/davidshepherd7/electric-operator/blob/dev/features/ess-mode.feature#L54
* Do you still need the `.+` one? I think I fixed a bug around that a while ago. See https://github.com/davidshepherd7/electric-operator/blob/dev/features/ess-mode.feature#L48
* What are you trying to achieve with the `!!` configuration? I've found code samples that don't add any spacing (e.g. https://www.r-bloggers.com/2019/07/bang-bang-how-to-program-with-dplyr/), which is what it seems to do at the moment.  (similarly for `!!!`) See https://github.com/davidshepherd7/electric-operator/blob/dev/features/ess-mode.feature#L63

**Comment by davidshepherd7** [comment]
I think this is all fixed now so I'll close this issue, but please reopen if there's still a problem :slightly_smiling_face:
