### ISSUE TITLE
feature request: support latex 

### ISSUE THREAD

**Issue by jthaman** [davidshepherd7/electric-operator#98]
I'd be nice if electric operator had some support for formatting latex equations, ie making them 'spacey'

Basic googling seems to indicate that there is no real latex style guide, but I think automatic spacing around binary operators and auto-spacing after commas could be useful. 

https://tex.stackexchange.com/a/12181/161372

**Comment by ywwry66** [comment]
I second this. But it may not be straightforward. For example, minus sign can be a dash or hyphen outside of math mode, where spaces are not appropriate.

**Comment by davidshepherd7** [comment]
Hi, I've added some basic support for a few obvious binary operators inside math mode (using auctex to check if it's inside math mode). It's been a few years since I wrote any latex though, can you two have a play with it and see what you think?

**Comment by ywwry66** [comment]
Thanks for doing this, it is great. One suggestion I have is when operators are used as superscripts/subscripts. For example, $\mathbb{R}_+$ and $\mathbb{N}^*$ are commonly used math symbols. So the desired behavior is not to insert spaces if `+` `-` `*` is right after `_` or `^`. Also, we would expect the same behavior if they are inside curly braces. The current behavior is like this: `{ +}` (note the extra space in front of `+` as compared to `(+)` and `[+]`)

**Comment by davidshepherd7** [comment]
Good catches! I think those cases should be handled now :slightly_smiling_face:

**Comment by ywwry66** [comment]
The curly braces problem is not totally fixed IMHO. The current behavior is `{ +}` `{ -}` and `{*}`, so it only works as expected when typing `*`. 

Looking at
https://github.com/davidshepherd7/electric-operator/blob/0819c449db35f728c14c17a471fa540ec1810974/electric-operator.el#L1277
I interpret this as the occurrence of `{` could make `+` or `-` a possible unary operator, like in `$e^{-x^2+1}$`. After the processing of `electric-operator`, this expression becomes `$e^{ -x^2 + 1}$`. But I think the space between `{` and `-` is unnecessary, and it looks better just to have `$e^{-x^2 + 1}$`.

I know this is all subjective, but you may think about this.

**Comment by ywwry66** [comment]
One bug I just found: `$1 +2$` is produced instead of `$1 + 2$`. Whereas `$a + b$` works just fine.

**Comment by davidshepherd7** [comment]
Yep, they were both bugs and both fixed now, thanks again!

Keep the bug reports/suggestions coming if you have more :)

**Comment by davidshepherd7** [comment]
I'll close this issue now since it seems like everything is working, but feel free to let me know if you run into anything else :slightly_smiling_face:
