### ISSUE TITLE
Remove the `(cons "?" "? ")` rule from ESS default 

### ISSUE THREAD

**Issue by ywwry66** [davidshepherd7/electric-operator#99]
In R, `?` is frequently used to access the documentation page of a function. The `(cons "?" "? ")` can mess with the prompt (`>`) in inferior-ess-r-mode. For example, if I want to learn about the function `plot`, I would type in `?plot`, and this becomes
```R
>? plot
```
while the expected behavior is
```R
> ?plot
```
(note that the trailing space after `?` is not necessary, and looking bad imo)

Of course I can remove the rule in my init file, but I think it is just better to change the default behavior.

**Comment by davidshepherd7** [comment]
Oh interesting, I didn't realise that R didn't have the common ternary operator meaning of `?`. Thanks for letting me know :+1:
